/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mumumusuc_loader_NativeLoaderTest */

#ifndef _Included_com_mumumusuc_loader_NativeLoaderTest
#define _Included_com_mumumusuc_loader_NativeLoaderTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mumumusuc_loader_NativeLoaderTest
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mumumusuc_loader_NativeLoaderTest_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
